# Generated by Django 4.0.2 on 2022-03-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
